name: Update Recent Blog Posts

on:
  schedule:
    - cron: '0 0 * * 0' # Run once a week at 00:00 (midnight) on Sunday
  workflow_dispatch:

jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: python/setup-python
      with:
        python-version: 3.11

    - name: Install poetry
      run: pip install poetry

    - name: Poetry install
      run: poetry install

    - name: Scrape posts and update README
      run: poetry run ./.github/scripts/update_posts.py
      env:
        GITHUB_TOKEN: $
        GITHUB_REPOSITORY: $
